# Generated by Django 5.0.3 on 2024-03-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testreport",
            name="report_file",
            field=models.FileField(upload_to="image/"),
        ),
    ]
