# Generated by Django 5.0.3 on 2024-03-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_testreport_report_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testreport",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testreports_as_doctor",
                to="patients.patient",
            ),
        ),
    ]
