# Generated by Django 5.0.3 on 2024-03-27 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_alter_testreport_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testreport",
            name="doctor",
        ),
        migrations.AlterField(
            model_name="testreport",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testreports_as_doctor",
                to="patients.patient",
            ),
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
